export const skills = [
  "JavaScript ES6+",
  "React",
  "Redux-Saga",
  "Redux (Toolkit)",
  "React Hooks",
  "React Router",
  "Semantic & accessible HTML",
  "Responsive Web Design",
  "CSS BEM convention",
  "CSS Grid",
  "CSS Flexbox",
  "Working with API (axios)",
  "Teamwork",
  "Markdown",
  "Immutability",
  "Error handling",
  "Promises, Async/Await",
  "GitHub Pull Requests & Review",
  "Trello",
  "Scrum",
  "NPM",
  "Git",
];

export const nextSkills = [
  "Typescript",
  "Node.js",
  "Unit testing",
  "React Context",
  "Cypress",
];
